apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"            
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DOMAIN
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_CORS_ORIGINS
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SECRET_KEY
        - name: FIRST_SUPERUSER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FIRST_SUPERUSER_PASSWORD
        - name: USERS_OPEN_REGISTRATION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USERS_OPEN_REGISTRATION
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SMTP_HOST
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SMTP_PASSWORD
        - name: EMAILS_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAILS_FROM_EMAIL
        - name: POSTGRES_SERVER
          value: postgres
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PASSWORD
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SENTRY_DSN
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80